package com.tdp2.setsubi.android_tp_sistema_de_inscripciones.Serializer;

public class JsonKeys
{
    public static final String ID = "id";
    public static final String NAME = "name";
    public static final String CODE = "code";
    public static final String CREDITS = "credits";
    public static final String DEPARTMENT = "department";
    public static final String VACANCIES = "vacancies";
    public static final String TEACHER = "teacher";
    public static final String TEACHERS = "teacher_courses";
    public static final String STUDENTS = "students";
    public static final String SCHOOL_TERM = "school_term";
    public static final String YEAR = "year";
    public static final String TERM = "term";
    public  static final String DATE_START = "date_start";
    public static final String DATE_END = "date_end";
    public static final String LESSON_SCHEDULES = "lesson_schedules";
    public static final String TYPE = "type";
    public static final String DAY = "day";
    public static final String HOUR_START = "hour_start";
    public static final String HOUR_END = "hour_end";
    public static final String EMAIL = "email";
    public static final String PASSWORD = "password";
    public static final String CLASSROOM = "classroom";
    public static final String NUMBER = "number";
    public static final String BUILDING = "building";
    public static final String FLOOR = "floor";
    public static final String ACCESS_TOKEN = "access_token";
    public static final String COURSE = "course";
    public static final String LAST_NAME = "last_name";
    public static final String INSCRIBED = "inscribed?";
    public static final String CONDITION = "condition";
    public static final String EXAM = "exam";
    public static final String DATE_TIME = "date_time";
    public static final String ACCEPTS_FREE_CONDITION = "accept_free_condition_exam";
    public static final String COURSES = "courses";
    public static final String SUBJECT = "subject";
    public static final String ENROLMENT = "enrolment";
    public static final String STATUS = "status";
    public static final String ENABLED_TO_ENROL = "able_to_enrol?";
    public static final String TEACHING_POSITION = "teaching_position";
    public static final String REGISTRATION = "registration";
    public static final String DATE_START_WEEK = "date_start_week";
    public static final String FINAL_QUALIFICATION = "final_qualification";
    public static final String UPDATED_AT = "updated_at";
    public static final String QUALIFICATION = "qualification";
    public static final String USER = "user";
    public static final String PRIORITY = "priority";
    public static final String SCHOOL_DOCUMENT_NUMBER = "school_document_number";
    public static final String FIRST_NAME = "first_name";
}
